<?php 

/**
 * Implements hook_theme().
 */
function social_post_feed_theme() {
  return [
    'ig_postfeed' => [
      'variables' => [
        'nodes' => NULL,
      ],
      'template' => 'ig-postfeed',
    ],
    'fb_postfeed' => [
      'variables' => [
          'objects' => NULL,
      ],
      'template' => 'fb-postfeed',
    ],
    'tw_postfeed' => [
      'variables' => [
          'tweet' => NULL,
      ],
      'template' => 'tw-postfeed',
    ],
    'yt_postfeed' => [
      'variables' => [
          'video' => NULL,
      ],
      'template' => 'yt-postfeed',
    ]
  ];
}
