<?php 

function swedishamerican_providers_theme($existing, $type, $theme, $path) {
    return [
        'providers_feed' => [
            'variables' => [
                'nodes' => NULL
            ],
            'template' => 'providers-feed',
        ],
        'providers_card_form' => [
            'variables' => [
                'locations' => NULL,
                'specialties' => NULL
            ],
            'template' => 'providers-card-form',
        ]
    ];
}
