<?php 

function swedishamerican_card_backs_theme($existing, $type, $theme, $path) {
    return [
        'location_form' => [
            'variables' => [
                'locations' => NULL
            ],
            'template' => 'location-form',
        ],
        'event_form' => [
            'variables' => [
                'events' => NULL
            ],
            'template' => 'event-form',
        ],
        'provider_form' => [
            'variables' => [
                'locations' => NULL,
                'specialties' => NULL
            ],
            'template' => 'provider-form',
        ]
    ];
}